/**
 * Auto-generated TypeScript types from OpenAPI specification
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is generated automatically from: https://api.project100x.run.place/api/openapi.json
 * 
 * To regenerate, run: npm run generate:api-types
 * 
 * Generated at: 2025-01-27T00:00:00.000Z
 */

// This file will be generated by the script
// Run: npm run generate:api-types

